application: cooptdm
version: 1
runtime: php
api_version: 1
tradesafe: true

handlers:
- url: /
  script: index.php
  login: optional

- url: /([^/]+\.php)
  script: \1
  login: optional

- url: /api/(.+\.php)$
  script: /api/\1
  login: optional

- url: /admin/(.+\.php)$
  script: admin/index.php
  login: admin
